### ISSUE TITLE
button text not properly vertically aligned on Firefox (Linux)

### ISSUE THREAD

**Issue by fkooman** [kevquirk/simple.css#1]
![image](https://user-images.githubusercontent.com/616885/103490195-185c1d80-4e12-11eb-8ec4-4612d92504a0.png)

Firefox 84.0.1 (64-bit) on Fedora 33.

**Comment by kevquirk** [comment]
Can you tell me which font from the stack is being rendered on your system please? I need to see if I can replicate this. My Ubuntu 20.04 system running Firefox 84.0 renders `Nimbus Sans L` and I don't see the issue:

![](https://i.imgur.com/ICT14SJ.png)

**Comment by fkooman** [comment]
![image](https://user-images.githubusercontent.com/616885/103519359-4d498e00-4e6d-11eb-91cd-f9ecc3c9ec92.png)

**Comment by fkooman** [comment]
It does properly on Chromium on the same system by the way. It seems there Liberation Sans is used if I understand the Chromium dev tools correctly...

**Comment by kevquirk** [comment]
Thanks for the info, I'll look into it.

**Comment by fkooman** [comment]
when I remove `Nimbus Sans L` from the list of fonts, the problem goes away. It doesn't appear to be a font that I have installed on my system...

Bootstrap reboot (https://github.com/twbs/bootstrap/blob/main/dist/css/bootstrap-reboot.css#L22) uses this which works fine for me, but maybe there are good reasons not to follow this...

```
  --sans-font: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", "Liberation Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
```

What is your source for the list of (system) fonts?

**Comment by kevquirk** [comment]
I can't replicate this issue. Does the problem occur on my personal site? https://kevq.uk (it's using the same font stack)

**Comment by fkooman** [comment]
Yes... Maybe I am the only one with this problem, could very well be... I may have installed some fonts at some point in the past that are not "default". I also just tested it on Debian 10 in Firefox, there it is fine... Thanks!

**Comment by riksoft** [comment]
I don't use simple.css but I've find this page looking for the same problem.
I can confirm the same problem with Firefox ESR and Firefox last version Developer Edition, both on Debian 11. The problem is the font, but I don't have any added font, only standard fonts that comes with the distro.

Try this on Debian 11
```
<html>
	<head>
		<title>TODO supply a title</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>
		<button style="font-size:42px;">Today</button> Aligned bottom<br>

		<button style="font-size:42px; font-family:courier">Today</button>Aligned top<br>

		<button style="font-size:42px; font-family:Georgia">Today</button>Aligned center<br>
	</body>
</html>
```
