### ISSUE TITLE
Boundaries between multiple sections have doubled lines

### ISSUE THREAD

**Issue by Swiddis** [kevquirk/simple.css#105]
When using multiple `<section>`s next to each other, the border between them is created by both elements. This looks awkward compared to having a single border with less padding.

## Expected Behavior

If two `<section>`s are next to each other, only one dividing border should be shown.

## Actual Behavior

The two `<section>`s share boundaries.

## Possible Solution

A simple workaround is to add a rule which removes the top border and padding from a section that follows another section:

```css
section + section {
    border-top: 0;
    padding-top: 0;
}
```

This causes expected behavior if added to the below page.

A more robust solution might also include handling for if a `<section>` is at the start or end of a container. Having leading or trailing borders that have nothing before or after them also looks off. This could possibly be implemented with clever usage of the `:last-of-type` selector.

Another alternative is that this is working as intended, and for this type of behavior a user should separate with `<hr>`s.

## Steps to Reproduce

A simple example page:

```html
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.simplecss.org/simple.css">
    </head>
    <body>
        <main>
            <h1>A page</h1>
            <p>Sample leading content</p>
            <section>
                <h2>Section 1</h2>
                <p>Some content</p>
            </section>
            <!-- Diplays 2 lines, should display 1 -->
            <section>
                <h2>Section 2</h2>
                <p>More Content</p>
            </section>
            <p>Sample trailing content</p>
        </main>
    </body>
</html>
```

**Comment by lkhrs** [comment]
I agree, the doubled lines look awkward. I like your solution for sections that are next to each other, and I also like your idea of hiding borders when a section is the first or last of its type in a container.

If you open a PR with these changes, I'd be happy to review and add them in.
