### ISSUE TITLE
Add cards

### ISSUE THREAD

**Issue by jeifour** [kevquirk/simple.css#108]
This is a proposal to add cards. Nothing fancy of course.
Maybe similar looking to the cards in https://andybrewer.github.io/mvp/mvp.html

Rationale: If I want to present multiple simple options or talking points on a page, but don't want it to look quite so empty, then both the navigation and classic lists don't really cut it. I feel like it is also an overall quite simple design element and would fit the project.

**Comment by kevquirk** [comment]
If you can think of a way to add them without classes, please submit a PR. :-)
