### ISSUE TITLE
The version from unpkg and the cdn are different

### ISSUE THREAD

**Issue by djmtype** [kevquirk/simple.css#109]
https://unpkg.com/simpledotcss/simple.min.css and https://cdn.simplecss.org/simple.min.css are not the same! 
For example, the stylesheet from unpkg has `img, video { max-width: 100% }` under `main` element. 

See diffchecker: https://www.diffchecker.com/dqoahCvi

**Comment by lkhrs** [comment]
Correct. Unpkg provides the latest release (currently 2.1.0), and the simple.css CDN provides the latest commit of the file from the GitHub repo.

**Comment by waldyrious** [comment]
Perhaps this could be made a little more explicit in https://github.com/kevquirk/simple.css/wiki/Getting-Started-With-Simple.css? I would have done the edit myself, but it seems that page is only editable by people with write access to the repo.

**Comment by kevquirk** [comment]
I've just published a new release (2.1.1) that brings them inline.

**Comment by waldyrious** [comment]
I understand the discrepancy, and even think it may be desirable (allowing people to choose between using the bleeding edge vs. the latest release of the stylesheet). I just think the wiki could make this distinction explicit just to ensure people aren't confused and assume they're supposed to be the same :)
