### ISSUE TITLE
publishing to npm

### ISSUE THREAD

**Issue by thescientist13** [kevquirk/simple.css#11]
Was just curious if there was any interest in [publishing](https://docs.npmjs.com/cli/v6/configuring-npm/package-json) this project to [**npm**](https://www.npmjs.com)?

I think this would be especially helpful for those who might want to depend on this project via a package manager like `npm` or `yarn`, e.g.
```sh
$ npm install simple.css
```

which would then support continued use and upgrades via _package.json_
```json
"dependencies": {
  "simple.css": "^1.0.0"
}
```

Additionally, I'm pretty sure this would also have a knock on effect of making this automatically available via tools like [**unpkg**](https://unpkg.com), so users could also just pop this into a `<link>` tag as well, e.g.
```html
<link rel="stylesheet" href="https://unpkg.com/simple.css/simple.css">
```

----

To implement, the following steps would need to be taken (and I can help by submitting a PR for steps 1 + 2)
1. Add a _package.json_ to the project with minimum needed keys like `name`, `files`, etc
1. Update _README.md_ / website with different options for usage / installation (package manager, unpkg, copy / paste)
1. Publish (by the maintainer) and test 🤞

**Comment by kevquirk** [comment]
Hey,

Sorry for the delay on responding to this. I think it's a great idea. If you want to submit a PR for steps 1 and 2, I'll so what's needed from my side so we can (hopefully) make this happen.
