### ISSUE TITLE
Horizontal rules could probably do with more spacing

### ISSUE THREAD

**Issue by binyomen** [kevquirk/simple.css#115]
I'm not a big user of horizontal rules, but I just put one in among a bunch of paragraphs and it seems like it might look better to increase the spacing. Here it is at the current value of `1rem`:

![image](https://user-images.githubusercontent.com/2928612/191912045-20ee4737-e636-4dcf-bcd7-8fc9da14d82c.png)

And here it is with `3rem`:

![image](https://user-images.githubusercontent.com/2928612/191913062-add29e5f-99df-43da-aaeb-8ecbd4270d3d.png)

I personally think `3rem` looks like a good value, but I'm open to suggestions.

**Comment by kevquirk** [comment]
Yeah, I think you're right. I don't really use them either, which is probably why this has been overlooked. :-)

Looking at the screenshots, I wonder if the HR needs more contrast too. What do you think @lkhrs?

**Comment by binyomen** [comment]
Hmm, yeah, more contrast could also make sense.

It also looks a bit weird to me at full text width. Putting it at like 40% looked a bit better to me, but I didn't experiment much with alternatives.

**Comment by binyomen** [comment]
The contrast ratio for the the horizontal rule is 2.8:1 according to WAVE. In light mode it's 1.39:1. According to [Understanding Success Criterion 1.4.11: Non-text Contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html), this fails the level AA (I'm not sure there's a level AAA for non-text contrast) standard of 3:1. Dark mode just barely fails, but light mode fails by more of a margin.

**Comment by lkhrs** [comment]
> Looking at the screenshots, I wonder if the HR needs more contrast too. What do you think @lkhrs?

Agreed, I opened #117 with decreased lightness on the border color to bring it up to spec (>3:1). I used the same color for the dark mode borders as well. Let me know what you think.
