### ISSUE TITLE
How to switch dark/light theme manually?

### ISSUE THREAD

**Issue by xyingsoft** [kevquirk/simple.css#123]
I would like to switch theme manually using data attribute of html tag.
For instance, `<html data-theme="light">` should apply light theme.

I am not sure how to switch dark/light theme manually for current version now.

**Comment by lkhrs** [comment]
Add this meta tag to your `<head>`:

```
<meta name="color-scheme" content="dark">
```

**Comment by xyingsoft** [comment]
I tried change `color-scheme` to `light`, but It doesn't seem to work, I only see dark colors. :(

**Comment by lkhrs** [comment]
Please share the code you're using. Pasting a minimal reproducible example here or a link to your GitHub repo (if public) would help.

**Comment by xyingsoft** [comment]
My code: 
```
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="color-scheme" content="light">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>
```
