### ISSUE TITLE
[feature request] adding responsive grid system & header images

### ISSUE THREAD

**Issue by clidawg** [kevquirk/simple.css#125]
Hey,

i really like your simple.css and i would appreciate to welcome a responsive grid system. Future its would be nice to welcome some css for logo images in header.

**Comment by kevquirk** [comment]
Simple.css already uses grid. Albeit a simple grid, but it can be easily overridden in custom CSS.

As for images in the header, that's also easy to add in your own CSS:

```
header img {
Your CSS here
}
```
