### ISSUE TITLE
Add header padding when there is no top navs.

### ISSUE THREAD

**Issue by H31t0rGamer** [kevquirk/simple.css#128]
Just add this to the css file:

			body > header:first-child:has(nav:not(:first-child), :not(nav)) {
				padding-top: 2rem;
			};

**Comment by lkhrs** [comment]
What does this fix exactly?On Dec 1, 2022, at 19:24, H31t0rGamer ***@***.***> wrote:﻿
Just add this to the css file:
body > header:first-child:has(nav:not(:first-child)) {
padding-top: 2rem;
};
