### ISSUE TITLE
Buttons stay highlighted after clicking

### ISSUE THREAD

**Issue by Visne** [kevquirk/simple.css#129]
Buttons stay highlighted after clicking, until you click somewhere else:

https://user-images.githubusercontent.com/39844191/208554539-ed519dab-7b30-42d2-a543-0d7be457bbd2.mp4

Expected behavior would be that the buttons stops being highlighted after the mouse stops hovering over it.

Seems to happen with Firefox 108.0.1 and Chromium 108.0.5359.124.

**Comment by lkhrs** [comment]
Hi Visne,

I can't reproduce this issue on Chromium/Firefox 108 and Safari 16.2 on macOS 13.1. Which OS are you running?

**Comment by kevquirk** [comment]
The `:focus` pseudo element is important, especially when it comes to forms that have more than one button. It allows the users to know which button is focussed (clicked). If you click off the button, anywhere on the screen, it will return to normal.

**Comment by waldyrious** [comment]
In my experience, when focus is visibly indicated, it tends to be via an outline (traditionally dashed/dotted, but I've been seeing solid outlines more often recently). GitHub does this, for example:

![image](https://user-images.githubusercontent.com/478237/208641785-8fb8dc10-8cd9-4796-9707-85193b3af533.png)

I think an outline may be more intuitive than a brightness increase, especially since the brightness change is also used to indicate a hovering status, making its meaning ambiguous.

**Comment by Visne** [comment]
Yes, outline is the [preferred way](https://www.a11yproject.com/posts/never-remove-css-outlines/) of showing this, and since outlines are not removed by SimpleCSS this is already covered. Buttons staying highlighted after clicking them and moving the cursor off feels unnatural, and if you look at buttons used around the internet/GUI locations you will see that usually it doesn't stay highlighted (assuming nothing is toggled), even though you can still use it with tab-navigation just fine because of the outline.

**Comment by kevquirk** [comment]
I think I misunderstood the issue here - when I look back at your original post, I'm struggling to understand what the issue actually is here. You're clicking and dragging the mouse, and the colour stays the same until you release the button?

I don't understand. I can't replicate a way of making the button stay "bright". What browser are you using?

**Comment by Visne** [comment]
No, I'm not dragging, just clicking the button.

To recreate:
1. Go to https://simplecss.org/demo
2. Scroll down to the section `Links & Buttons`
3. Click the `I'm a button` button
4. Move your mouse of the button (don't drag)

Actual behavior: the button stays highlighted
Expected behavior: the button stops being highlighted

**Comment by badcat** [comment]
I can replicate this behavior on many sites - even Google, YT..

- Click on the button.
- Then without releasing the mouse button move/slide the mouse cursor out of the focusable area.
- _Then_ release the mouse button - the button stays highlighted.

From what I see this seems like the normal and expected behavior of the web with current browsers.

**Comment by Visne** [comment]
> Then without releasing the mouse button move/slide the mouse cursor out of the focusable area.
Then release the mouse button - the button stays highlighted.

This issue isn't about dragging the mouse.

**Comment by badcat** [comment]
> > Then without releasing the mouse button move/slide the mouse cursor out of the focusable area.
> > Then release the mouse button - the button stays highlighted.
> 
> This issue isn't about dragging the mouse.

Understood - perhaps my description wasn't dead on - but the click button behavior of many sites is similar in how the focus highlight shows up.. I think.   Here's Google...  my "click" is shown with the circle.

https://user-images.githubusercontent.com/26096/208771635-a24c6775-9b17-4d58-b26f-a500ffbc4e44.mov

**Comment by Visne** [comment]
Probably because that button is normally supposed to take you to another page, so it doesn't really matter. But if you for example star this repo, or unsubscribe from notifications, you will see that it doesn't stay highlighted.

**Comment by badcat** [comment]
But those are more than just <button>blah</button> in that they're often in form elements, have JS attached etc, no?

**Comment by badcat** [comment]
Maybe you want to add your own CSS?
Something like...

``
button:active {
  background-color:red;
}
``

**Comment by Visne** [comment]
> Maybe you want to add your own CSS?

I've already fixed it by using

```css
	button:focus,
	[role="button"]:focus,
	input[type="submit"]:focus,
	input[type="reset"]:focus,
	input[type="button"]:focus,
	label[type="button"]:focus {
		filter: unset;
	}
```

> But those are more than just blah in that they're often in form elements, have JS attached etc, no?

That shouldn't be relevant for UX design.

**Comment by badcat** [comment]
OK :) maybe this isn't the repo you're looking for? 🪄

**Comment by Visne** [comment]
It already does what's needed, because I can just overwrite it like I have done. Still, I would like to discuss the problem so it can possibly be fixed, instead of being told to find another project.

**Comment by badcat** [comment]
Oh my - I'm not a maintainer here, was only trying to help with an alternate suggestion.

**Comment by 81Denton** [comment]
What part of the problem does "go to another repo" solve?

**Comment by lkhrs** [comment]
We're getting a bit off topic here.

I do think the focus issue needs to be addressed. One scenario would be using a button for JavaScript events without navigation. Currently, clicking the button would leave it with the highlight effect until the next click on the page, which is not ideal.

I'll start working on a fix tonight.

**Comment by kevquirk** [comment]
> No, I'm not dragging, just clicking the button.
> 
> To recreate:
> 
> 1. Go to https://simplecss.org/demo
> 2. Scroll down to the section `Links & Buttons`
> 3. Click the `I'm a button` button
> 4. Move your mouse off the button (don't drag)
> 
> Actual behavior: the button stays highlighted Expected behavior: the button stops being highlighted

This doesn't happen for my on Safari on MacOS. I can't replicate the issue.

**Comment by kevquirk** [comment]
I can replicate it in Firefox.

**Comment by lkhrs** [comment]
Adding a datapoint: I can replicate this in Chromium and Firefox, but not in Safari.

**Comment by walterdavis** [comment]
You might want to look at a completely bare HTML-only page with a button on it and see how that behaves in the various browsers with just their user-agent styling. It's my recollection that clicking down on a button and then sliding off of it before releasing the mouse/trackpad (thus sending the mouseup event) causes that button to lose its "pressed" styling, just as if you had never clicked it.

**Comment by Visne** [comment]
HTML file with
```html
<button>I'm a button</button>
```
has the behavior in Firefox and Chromium that the button stops being highlighted after moving the mouse off, which is what I would expect.

**Comment by waldyrious** [comment]
@lkhrs I think your changes ([cfa445a](https://github.com/lkhrs/simple.css/commit/cfa445aa2695707c468c4c173aa78e1fd2d745e7)) do address this issue, but I would suggest also adding specific styles for focused buttons in a way that matches the rest of the stylesheet, rather than removing the custom focus styles altogether.

**Comment by Visne** [comment]
> @lkhrs I think your changes ([cfa445a](https://github.com/lkhrs/simple.css/commit/cfa445aa2695707c468c4c173aa78e1fd2d745e7)) do address this issue, but I would suggest also adding specific styles for focused buttons in a way that matches the rest of the stylesheet, rather than removing the custom focus styles altogether.

If you do, please use [`:focus-visible`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) instead. This will apply the style when a keyboard-only user is navigating the page, but it will not apply the style after a normal left-click, which is distracting.
