### ISSUE TITLE
What are the changes in 2.1.2? Github release is absent (but 2.1.2 is present on npmjs)

### ISSUE THREAD

**Issue by mendhak** [kevquirk/simple.css#135]
Hi there, there's a new [2.1.2 release on npmjs](https://www.npmjs.com/package/simpledotcss?activeTab=versions) but I cannot see any git tag/github [release](https://github.com/kevquirk/simple.css/releases) in this repo. Please could you create one showing what the changes are? 

Much appreciated thanks!

**Comment by lkhrs** [comment]
Looks like the version numbers are out of sync. 2.1.2 on NPM is 2.1.1 on the repo.

**Comment by mendhak** [comment]
Hi I just had a look at the CSS files in the 2.1.1 and 2.1.2 packages and they're different.  What I did:


```bash
# Download the packages:
npm pack simpledotcss@2.1.1
npm pack simpledotcss@2.1.2

# Extract to directories:
tar -xzvf simpledotcss-2.1.1.tgz --one-top-level=package211
tar -xzvf simpledotcss-2.1.2.tgz --one-top-level=package212

# Open in compare tool:
meld package212/package/simple.css package211/package/simple.css
```

**Comment by mendhak** [comment]
Ah I see what you're saying, I compared the repo too, definitely the repo seems to match what's in 2.1.2:

```
git clone git@github.com:kevquirk/simple.css.git
meld simple.css/simple.css package212/package/simple.css
```

And the output shows no differences, but difference with 2.1.1.

**Comment by mendhak** [comment]
Thanks for clarifying, it is appreciated!
