### ISSUE TITLE
Introducing basic classes?

### ISSUE THREAD

**Issue by kevquirk** [kevquirk/simple.css#136]
Thinking about introducing a couple of classes to the project, that will hopefully improve things.

* `.button` that can be added to links in order to format them to look like a button
* `.notice` that can be added to a `p` element to make it a notice box.

Open to pushback/ideas on whether we should a) do this and b) other classes we should maybe think about.

This has been discussed before in #59

**Comment by lkhrs** [comment]
This is a great idea, and I agree with both the suggested classes.

I think we should avoid classes for CSS Grid or Flexbox. These are unique to each application, and trying to maintain a layout solution that works for the majority of use cases would be a bear of a task. There's plenty of drop-in layout frameworks that focus on this.

**Comment by badcat** [comment]
Looks like a super useful addition.  thank you.

**Comment by kevquirk** [comment]
This has been added in 2.2.0, but it's not live on NPM yet, as there's a problem with the GH action to deploy (#137). Will look at that ASAP.
