### ISSUE TITLE
Dark theme is missing `--marked` color

### ISSUE THREAD

**Issue by jsyrjala** [kevquirk/simple.css#139]
It should be explicitly defined also for dark theme?
Light theme:
https://github.com/kevquirk/simple.css/blob/main/simple.css#L19
Dark theme:
https://github.com/kevquirk/simple.css/blob/main/simple.css#L33

**Comment by kevquirk** [comment]
No, the same colour works well for both light and dark mode.

Light mode:
<img width="727" alt="Screenshot 2023-03-25 at 17 27 38" src="https://user-images.githubusercontent.com/16818377/227732439-9153738c-5f97-4004-b1d9-c41a2b4c9aeb.png">

Dark mode:
<img width="727" alt="Screenshot 2023-03-25 at 17 27 52" src="https://user-images.githubusercontent.com/16818377/227732454-7f0ff7b3-18d0-4a25-8c47-c14d08cc83bf.png">
