### ISSUE TITLE
The button class should have display as inline-block by default

### ISSUE THREAD

**Issue by cwylycode** [kevquirk/simple.css#142]
In the demo, you show a link with the button class, essentially turning the hyperlink into a clickable button. This is nice, but the button class doesn't have display set to inline-block, as it normally would be for an actual button element. As a result, having multiple link buttons strung together that overflow become mangled due to word wrap and text line spacing.

This can be easily fixed by applying `display: inline-block;` to the button class.

Example ('a' tag links with normal button class applied on each link):
![image](https://user-images.githubusercontent.com/69492910/230959472-f1bced66-b694-4f43-a481-78274d59005c.png)

Fix with display property set to inline-block on button class:
![image](https://user-images.githubusercontent.com/69492910/230959879-d9a6820b-5722-4424-bf65-9b42d92f46f0.png)

This works to fix inline elements with the button class added to them (span, a, etc...) and improves elements that are already block elements (h's, p, etc...) with a button class added.

Can this be fixed? Or would there be some problem with implementing it (i.e. break something)? Thanks!

**Comment by kevquirk** [comment]
Thanks for this, can't believe we missed it. Yay for open source! I just pushed a fix.
