### ISSUE TITLE
Typo in tag?

### ISSUE THREAD

**Issue by marcvs** [kevquirk/simple.css#144]
Most tags are similar to `v2.1.1`
The latest version is tagged as `v.2.2.0`

This causes trouble with automated downloads (e.g. for packaging)

**Comment by kevquirk** [comment]
Whoops, not sure how I managed to do that, but thanks for letting me know. I've just fixed it, so the latest release is now tagged `v2.2.0`.

https://github.com/kevquirk/simple.css/releases/tag/v2.2.0

**Comment by marcvs** [comment]
Thanks!
I've submitted a packaging request to debian[1] and to fedora[2], since my package "oidc-agent" depends on this.

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1034821
[2] https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2189488
