### ISSUE TITLE
Class for current nav item

### ISSUE THREAD

**Issue by helinwan** [kevquirk/simple.css#147]
Hi,

I want to suggest another basic class:  "nav > a.current".
Whenever I use the nav I want to visiualize the current item, like on the demo page.

Cheers

**Comment by kevquirk** [comment]
That's a great idea. @lkhrs what do you think about adding a `.current` class?

Here's what we use on the site:

```
nav a.current {
  color: var(--accent);
  border-color: var(--accent);
}
```

**Comment by lkhrs** [comment]
@kevquirk sounds good to me! I'll start working on it.

**Comment by lkhrs** [comment]
Yep, that's the right file. Have a look at the one used for the Simple.css site: https://github.com/kevquirk/simple.css-site/blob/main/_includes/navigation.html
