### ISSUE TITLE
npm does not serve the release code

### ISSUE THREAD

**Issue by helinwan** [kevquirk/simple.css#149]
Hi, the code on npm (https://www.npmjs.com/package/simpledotcss?activeTab=code) differs from the current release on GitHub (2.2.0).

**Comment by lkhrs** [comment]
Can confirm. Looks like some commits got tagged as v2.2.0 after the release.

```
❯ diff node_modules/simpledotcss/simple.css simple.css-2.2.0/simple.css 
2c2,3
< :root {
---
> :root,
> ::backdrop {
25c26,27
<   :root {
---
>   :root,
>   ::backdrop {
324c326
< article, fieldset {
---
> article, fieldset, dialog {
521a524
>   color: black;
624a628,637
> }
> 
> dialog {
>   max-width: 40rem;
>   margin: auto;
> }
> 
> dialog::backdrop {
>   background-color: var(--bg);
>   opacity: 0.8;
626a640,646
> @media only screen and (max-width: 720px) {
>   dialog {
>     max-width: 100%;
>     margin: auto 1em;
>   }
> }
> 
629a650,651
>   display: inline-block;
>   text-decoration: none;
```

**Comment by lkhrs** [comment]
@kevquirk should we republish the release to NPM or start a new release?

**Comment by kevquirk** [comment]
We will probably need to create a new tag and republish. I'll look into it today if I get time.

**Comment by kevquirk** [comment]
Had a bit of time this morning. Created `v2.2.1` and published it to NPM. Hopefully it will all match now.
