### ISSUE TITLE
you should make cdn links more visible

### ISSUE THREAD

**Issue by fountainpen** [kevquirk/simple.css#167]
most of such small css libraries like yours is , have cdn lihnk available on the first page, so I suggest the sane,

**Comment by fountainpen** [comment]
p.s.

 - you didnt update github release

**Comment by kevquirk** [comment]
Not sure what you mean. The CDN details are at the very top of the getting started page on the docs - https://github.com/kevquirk/simple.css/wiki/Getting-Started-With-Simple.css

**Comment by fountainpen** [comment]
I mean:

put those links as part of README.md file
and put them as part of your HTML file which presents your stylesheet.

[see how miligram did it, just for example: https://milligram.io]
