### ISSUE TITLE
Low contrast on some elements

### ISSUE THREAD

**Issue by paper42** [kevquirk/simple.css#17]
Lighthouse reports elements with low contrast in the light theme:
```
cite
```
and more in the dark theme:
```
cite
figcaption
p (in the footer)
```

Firefox accessibility tools say, that the elements have contrast ratio 4.08, but the minimal is 4.5. The recommended would be 7 which is exactly the contrast ratio of all other elements on the page. It's not only an opinion of some tools, I have hard time reading <cite> on worse, older screens.

**Comment by kevquirk** [comment]
OK. I've changed the following variable colours:

**Light theme:**
```
# Before
--text-light: #666; (ratio: 3.79:1)

# After
--text-light: #585858; (ratio: 7.11:1)
```

**Dark theme:**
```
# Before
--text: #ABABAB; (ratio: 7.01:1)
--text-light: #808080; (ratio: 4.07:1)

# After
--text: #DCDCDC; (ratio: 11:74:1)
--text-light: #ABABAB; (ratio: 7.01:1)
```

Everything should now conform to WCAG AAA contrast ratios. The only exception is inline `<code>` (the pink text) which has a ratio of around 5:1. I'm ok with this though, as `<code>` is generally used for very small amounts of text.

Thanks for the feedback, this was a great catch.
