### ISSUE TITLE
modern css reset

### ISSUE THREAD

**Issue by diomed** [kevquirk/simple.css#172]
hi

I suggest looking into this and adopting some of it, which isnt already in code:

https://andy-bell.co.uk/a-more-modern-css-reset/

**Comment by lkhrs** [comment]
I’ve read the article before but I think our existing reset rules are sufficient. If you have any specific suggestions of what to include and cases for why, I’d like to take a look. As it is we try to only reset what we need; leveraging user agent stylesheets can be a good thing.
