### ISSUE TITLE
Feature Request: Aside cards equally spaced

### ISSUE THREAD

**Issue by panigrc** [kevquirk/simple.css#173]
I want to achieve something like that ([Mvp.css](https://andybrewer.github.io/mvp/#docs)):

![image](https://github.com/kevquirk/simple.css/assets/645895/d0694538-53f1-4022-a1b4-44c394ebb365)

If I use 3 `<aside>` in a section with `simple.css` I get this:

![image](https://github.com/kevquirk/simple.css/assets/645895/63dea735-a77e-4f33-ac62-1ae24229d3f5)

Is there any way to solve that?

**Comment by kevquirk** [comment]
This really isn't the place for support requests on actually building your website, but this is a simple one, so I'll quickly answer it.

Three `aside` isn't the way to go here and I don't think it would be valid HTML, as that's not the proper use of the `aside` element. What you want is a flexbox with a few divs inside.

Here's a simple codepen I knocked on up how to do it - https://codepen.io/kevquirk/pen/OJrKrWE

**Comment by panigrc** [comment]
Thank you for your quick response!

Actually this wasn't a support request, but a feature request that perhaps you could embed to your css :slightly_smiling_face: .

But you are right, I've looked the documentation of [aside](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside) and it's meant to be used as you do it in `simple.css`  :+1: 

So thanks again for providing an example, I wanted to avoid classes, but it seems that there is no other option ... at least for now :smirk:

**Comment by kevquirk** [comment]
You won't be able to avoid the `flex-container` class, but you could limit the classes used by removing the `box` class and changing the CSS to this:

```
.flex-container > div {
    css for the `box` class
}
```
