### ISSUE TITLE
Please add Material Design

### ISSUE THREAD

**Issue by paolostefanucci** [kevquirk/simple.css#174]
I discovered SimpleCSS just yesterday, and I love it.
I code in vanilla PHP, and I don't like big Framework.
Congratulation for this great work.
It is great idea not use proprietary class, but modify the design of Plain HTML.

Please could you complete your wonderful simplecss, with some Material Design:
you can check https://github.com/finnhvman/matter and add just some class or attribute:

1) form input like text, email, textarea....
   I like so much the class="matter-textfield-outlined" with the label inside the box that on click go small in the upper border
  I suggest you to use a short class name like class="outline"
on codepen website there are other simple example of outlined input field

3) An "outline" button like we can find in the nav header menu in the simplecss

3) A Ripple effect when a button is pressed for normal and for outline button, without use a class="ripple"
on codepen website there are other simple example that use only css
https://codepen.io/finnhvman/pen/jLXKJw

4) Switched on and Switched off
https://raw.githubusercontent.com/finnhvman/matter/master/docs/hero.png

Thank you.
Paolo

**Comment by lkhrs** [comment]
Thank you for your suggestions, however they are outside the scope of the project at this time.
