### ISSUE TITLE
Button contents over saturated during hover

### ISSUE THREAD

**Issue by bas080** [kevquirk/simple.css#183]
Notice that the button is not looking good during hover state because the emoji is barely visible.

I'm not sure what to suggest as improvement.

No hover:
![2024-01-08-231514_2560x1440_scrot](https://github.com/kevquirk/simple.css/assets/1840380/834e5fb8-6c6d-4a90-8091-12bc24d6b122)

Hover:
![2024-01-08-231018_2560x1440_scrot](https://github.com/kevquirk/simple.css/assets/1840380/321e21e9-6424-46aa-88c1-6e74f3c0b1fa)

**Comment by lkhrs** [comment]
Looks like this is caused by `filter: brightness` on line 234.
https://github.com/kevquirk/simple.css/blob/8981244b535f3acc5a72c5f282949ebdd785d05d/simple.css#L234

I think the best way to solve this would be to use `background-color` for button hover state.

**Comment by bas080** [comment]
Thank you @lkhrs.
