### ISSUE TITLE
More accessible table

### ISSUE THREAD

**Issue by bas080** [kevquirk/simple.css#185]
When checking wcag compliance I noticed an issue with the tables. It results in a window x scrollbar.

The issue with a window x scrollbar:
![2024-01-23-140057_1239x1253_scrot](https://github.com/kevquirk/simple.css/assets/1840380/d26aef8e-d35a-4de6-9515-89738c058179)

Potential fix:
![2024-01-23-140604_268x76_scrot](https://github.com/kevquirk/simple.css/assets/1840380/76f4f42f-c80f-4669-8e21-d4ec51433c0f)

Without a window x scrollbar and instead a table overflow-y scrollbar.
![2024-01-23-140248_1255x1261_scrot](https://github.com/kevquirk/simple.css/assets/1840380/e7648b35-4b78-47b1-a24c-630a6331df53)

**Comment by lkhrs** [comment]
Hi bas080,

Would you mind sharing your markup?

Are you wrapping the table with a `<figure>` element? See https://github.com/kevquirk/simple.css/wiki/Utility-elements-and-classes#horizontal-scroller

**Comment by bas080** [comment]
I'm not wrapping in a figure. Didn't know wrapping tables in a figure is a
thing.

I'll opt-in to using a figure tag after reading the Mozilla docs on the
figure tag.

Maybe document this on the demo page in the tables section. I think it
would help people make better tables (x-scroll) and it nudges them to add a
caption.

Thanks for pointing this out!

**Comment by lkhrs** [comment]
Thank you, I’ll take a look at updating the demo page on the site.

And I forgot to add: changing the `display` property to anything other than `table` on a table makes it inaccessible to some screen reader/browser combinations. Wrapping it in another element which scrolls is a way to keep it accessible and still have horizontal scrolling. This could change in the future and we’re always open to accessibility PRs.

https://developer.mozilla.org/en-US/docs/Web/CSS/display#tables
