### ISSUE TITLE
`figure` image and caption are no longer aligned

### ISSUE THREAD

**Issue by mendhak** [kevquirk/simple.css#188]
Hi there, in v2.3.0 I noticed the figure image and caption are no longer aligned. 

I tried to recreate the issue, have a look at this fiddle, using v2.1.1: https://jsfiddle.net/ztp6bfng/  

And this one uses v2.3.0:  https://jsfiddle.net/dj8xn960/8/  

I believe the original PR that aligned them was #56 

This was undone in #104 

Screenshots: 
v2.1.1
![image](https://github.com/kevquirk/simple.css/assets/746276/df7af39b-b43e-49fe-838d-48525b1439ee)

v2.3.0
![image](https://github.com/kevquirk/simple.css/assets/746276/9ce008b3-598e-4997-bc9d-31935eedb9dd)

**Comment by lkhrs** [comment]
Removing `text-align: center;` from the `figure` element caused this. We don’t want all inline elements in a figure to be aligned center so I added a rule just for images in #189. 

Any suggestions before I merge?

**Comment by mendhak** [comment]
Hey thanks that's looking good. I just tried it in a JSFiddle and it seems to work well!  https://jsfiddle.net/zya1fxc3/2/

figure img and figure picture img makes sense. 

Question — I noticed the margin-bottom is replaced with a margin-block which adds spacing at the top, is that OK? Actually it doesn't look too bad but wanted to check that's what you expected. 

Old:
![image](https://github.com/kevquirk/simple.css/assets/746276/7745fb71-04e7-43b9-9101-09d02fd1e5a0)

New:
![image](https://github.com/kevquirk/simple.css/assets/746276/1355edc8-87f7-4271-a01f-293c5b780b13)

**Comment by mendhak** [comment]
Sad to see placekitten.com not working well any longer, I remember using it a long time ago.

**Comment by lkhrs** [comment]
Yeah with the switch to `display: block` on the `img`, the caption was too close. I switched `margin-bottom` to `margin-block` to fix that. Should help with other block elements as well.

And yeah I’m sad about placekitten too.
