### ISSUE TITLE
Why top margin for tables?

### ISSUE THREAD

**Issue by GitToTheHub** [kevquirk/simple.css#192]
Hi,

after working with your framework and using tables, i notice, that there are big gaps between text and the table top border. For example, if I do the following:

```
<p>
  A Caption
</p>

<table>
  ...
```

It will result in something like this:

<kbd><img width="418" alt="Bildschirmfoto 2024-05-18 um 09 02 48" src="https://github.com/kevquirk/simple.css/assets/13721821/f59b7d2c-e6dc-475f-a153-8fb2a30da9d2"></kbd>

When I set the table margin to `initial`, it results in something like this:

<kbd>
<img width="280" alt="Bildschirmfoto 2024-05-18 um 09 09 36" src="https://github.com/kevquirk/simple.css/assets/13721821/0932061f-2a2a-4cf8-80bb-bff704c5b49d">
</kbd>

What is the purpose of setting:

```
margin: 1.5rem 0;
```

in tables?

Regards, Manuel

**Comment by kevquirk** [comment]
To give the tables some breathing room. You can override it with custom CSS.

**Comment by GitToTheHub** [comment]
Ok, but when I combine it with a `p` there is much breathing room. I thought, it would be better, if the user would self decide if there is breathing room or not.

**Comment by GitToTheHub** [comment]
@kevquirk 

I see what's going on. When putting a `p` above a `table`, there is no big gap, as in my first screenshot. But when putting the table in a `figure`, there will be a big gap between the paragraph and the table. Example:
```
<p>A paragraph</p>
<figure> <!-- Produces big space between paragraph and table -->
  <table>
    <thead>
      <tr>
        <th>Header 1</th>
        <th>Header 2</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Column 1</td>
        <td>Column 2</td>
      </tr>
    </tbody>
  </table>
</figure>
```
Without the figure, everything is ok with the table and the paragraph.

**Comment by lkhrs** [comment]
This is a weird one. Top margin on a table is cancelled out when under a paragraph, but when the table is wrapped in a figure and is wider than the container we get both margins.

We can fix this by setting `margin: 0` on the `figure > table` selector, but I will need to test this further.

**Comment by GitToTheHub** [comment]
Hi @lkhrs,

> We can fix this by setting margin: 0 on the figure > table selector, but I will need to test this further.

I tested it and it works for paragraphs, but when writing text without a paragraph above the figure, the text has no spacing to the figure. Maybe you find a solution for it.

Thanks!

**Comment by lkhrs** [comment]
The solution is to use a paragraph. We cannot support writing text without the appropriate elements.
