### ISSUE TITLE
Print the button text only

### ISSUE THREAD

**Issue by GitToTheHub** [kevquirk/simple.css#195]
Hi,

I want to print for some buttons the text only. Could you add a class or another solution for it?

Regards, Manuel

**Comment by kevquirk** [comment]
I don't understand the details around what kind of class you want, but we don't plan on adding any new classes in the near future. This is something that would come under [personal customisations](https://github.com/kevquirk/simple.css/wiki/Getting-Started-With-Simple.css#customise-simplecss)

**Comment by GitToTheHub** [comment]
Ok let me explain. I want to print a table which contains buttons and the buttons contains text, which should be printed but not the button itself, means background-color and border. There could be a class, e.g. „print-button-text-only“, which does this. I tried to do it self by setting background-color to transparent and border to 0 in a print media-query, but it didn’t work in Safari on macOS.

I‘m wondering, that you write, that you don’t plan to add any new classes in the near future, because you write on your website, that new classes could be added by making an issue on github: https://simplecss.org/introducing-simple-classes

 Of course, you can do what you want 🙂

Thanks for your support and your framework anyway 🙂

**Comment by kevquirk** [comment]
If it's something that would be broadly used, then we would *consider* adding it. This is a very niche use case though, and still very much in the realms of custom CSS.

**Comment by GitToTheHub** [comment]
Ok thanks, I understand. I thought i could improve the framework.

Regards
