### ISSUE TITLE
Helper class to disable simple css for an island/section of the dom

### ISSUE THREAD

**Issue by bas080** [kevquirk/simple.css#196]
Simplecss has the defaults I like but they also apply to widgets I want to use. As a result my web components can look different or not be functional.

```html

<body>
...
<div class="no-simplecss"
  <markdown-editor>
  </markdown-editor>
</div>
...
</body>
```

Possible implementation using sass. Haven't tried.

```sass

html *:not(.no-simplecss) * {
  /* simplecss css ruls */
}

```

![2024-06-03-154136_936x501_scrot](https://github.com/kevquirk/simple.css/assets/1840380/46356503-683c-40a5-92b8-be46ab8b4e2c)
![2024-06-03-154125_922x544_scrot](https://github.com/kevquirk/simple.css/assets/1840380/729dfeff-0505-4398-886d-bab6e2394add)

**Comment by lkhrs** [comment]
Hi @bas080,

Wrapping the entirety of Simple.css with a selector to enable this feature would be impractical. You’re welcome to accomplish this in your own project however you see fit.

The need to override cascading styles at the component level is a classic problem for JavaScript embeds, and web components are an upgraded version with the same issue. I recommend embracing the cascade and carefully defining overrides where needed. 

It appears the main issue with your component is related to the icons in the toolbar, which might use an icon font. Maybe a single selector in your component’s CSS with overrides for font size and line height would solve the issue you’re seeing.

**Comment by bas080** [comment]
lkhrs, why would it be impractical? Would it have an unreasonable cost of some sort?

**Comment by lkhrs** [comment]
> lkhrs, why would it be impractical? Would it have an unreasonable cost of some sort?

Yes, there are at least two unreasonable implementation costs to this approach:
1. Overriding the _entire_ cascade
2. Adding a preprocessor and supporting its complexities (CSS nesting is still new)

> @lkhrs , you also mention that this is _a classic problem for JavaScript embeds_. What if simplecss offers the tools to deal with such a problem.

CSS already offers the tools to deal with this problem: selectively override the cascade on your component’s elements on a per-property basis.

**Comment by bas080** [comment]
@lkhrs , thank you for taking the time to share your reasoning. 

I ended up using an iframe which is the quickest non tedious thing I could think of.
