### ISSUE TITLE
Shows input with hidden attribute

### ISSUE THREAD

**Issue by bas080** [kevquirk/simple.css#197]
The browser default is to hide input fields with attribute hidden. Simple overwrites this default which I believe is undesirable.

![2024-06-06-220705_731x119_scrot](https://github.com/kevquirk/simple.css/assets/1840380/dfb7d5f9-30f6-4e8e-a6f9-4408c769b637)
![2024-06-06-220712_412x111_scrot](https://github.com/kevquirk/simple.css/assets/1840380/9e6b529d-2c86-436c-a49b-5edbdee04c28)

**Comment by xrat** [comment]
Shouldn't this be `<input type="hidden" ...`?

**Comment by lkhrs** [comment]
@xrat is correct here. The `hidden` attribute is a semantic shortcut for `style="display: none"`, which should not be used on input elements because it may result in unexpected behavior. See these StackOverflow answers:
https://stackoverflow.com/a/13422440
https://stackoverflow.com/a/68745881
