### ISSUE TITLE
colour highlight for `<ins>` and `<del>` elements

### ISSUE THREAD

**Issue by Johann150** [kevquirk/simple.css#198]
In most contexts it might make sense to highlight `<ins>` and `<del>` elements more than they already are. In Firefox they are for me displayed as underlined text (ins) or strikethrough text (del). For me this does not really make their semantics clear. As I'm used to it from git, it makes sense for me to also add e.g. green (ins) or red (del) text colours into the mix.

Though I'm not sure how this works out with e.g. accessibility for contrast or for people with colour blindness. I guess it could be seen as an additional cue/helper for people who can work with it? But I'm not sure, so making this issue to hear some opinions first.

P.S.: noticed this while adding simple.css to my own website and I think it's really nice, thanks! :)

**Comment by lkhrs** [comment]
Hi @Johann150,

While I agree that the default semantics aren't as clear as your example and [the example on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ins), these are niche inline elements and including styles for them would be extra lines that would go unused most of the time. I recommend adding custom CSS for these if you use them.
