### ISSUE TITLE
Considering relicensing to something more permissive?

### ISSUE THREAD

**Issue by prologic** [kevquirk/simple.css#2]
This is a great CSS library. Reminds me of [PicoCSS](https://picocss.com). Would you consider relicensing this to something a bit more permissive and liberal like MIT or BSD?

**Comment by kevquirk** [comment]
> This is a great CSS library. 

Thank you.

> Would you consider relicensing this to something a bit more permissive and liberal like MIT or BSD?

I'm far from an OSS licensing expert, I always thought GPL was the most permissive, is that not the case? If MIT or BSD are more permissive than the GPL, then I'm happy to change the license.

**Comment by prologic** [comment]
> I'm far from an OSS licensing expert, I always thought GPL was the most permissive, is that not the case? If MIT or BSD are more permissive than the GPL, then I'm happy to change the license.

Github actually [documents this](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository) quite well and even created a [tool](https://choosealicense.com/) to help developers choose the _right_ license.

For me, [MIT License](https://opensource.org/licenses/MIT) has always been the license of choice as it is quite permissive and simple to understand. I'm not a lawyer either, so don't take my word for it :D

**Comment by kevquirk** [comment]
Changed to the MIT license. I didn't realise the GPL didn't allow for close source redistribution. Thanks for the help!
