### ISSUE TITLE
Accordian

### ISSUE THREAD

**Issue by Laaniya** [kevquirk/simple.css#202]
Hi,
Please can you create a style in the theme for the accordion class?
Thank you.
Laaniya

**Comment by kevquirk** [comment]
We already have an "accordion" within standard HTML, it's the `details` element which is already styled within Simple.css.

```
<details>
  <summary>Accordion title</summary>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
</details>
```

There is no need for an additional class to achieve this.
