### ISSUE TITLE
Scrollbar shifts position of main content

### ISSUE THREAD

**Issue by navadev** [kevquirk/simple.css#204]
Hello,

As can be seen in the animation below, the appearance of the vertical scrollbar causes a visible shift of the main area. Is there a way to avoid this? Is this expected behavior?

![toggle-scrollbar](https://github.com/user-attachments/assets/4909fb9a-edb5-4b9a-80b1-1e0eb04d121e)

**Comment by lkhrs** [comment]
This is expected behavior.
