### ISSUE TITLE
Add a max-width to the td table for more useful columns 

### ISSUE THREAD

**Issue by united-for-palestine** [kevquirk/simple.css#212]
## Before
![2024-10-24-151834_408x497_scrot](https://github.com/user-attachments/assets/94fcf2de-0c8b-44d6-b238-54ef0d4d8fb5)
![2024-10-24-151825_431x497_scrot](https://github.com/user-attachments/assets/f39b256a-0c9a-4721-8f98-1082750282fc)
![2024-10-24-151810_417x515_scrot](https://github.com/user-attachments/assets/525845a1-5e83-4b3c-af1a-cf1e8155394f)
![2024-10-24-151754_412x552_scrot](https://github.com/user-attachments/assets/560a613f-8b15-4010-93b9-7ae46752685a)

## After
![2024-10-24-152015_421x732_scrot](https://github.com/user-attachments/assets/e1e1cd73-b41d-439f-9fa6-79cc6bb5ec28)
![2024-10-24-152003_375x735_scrot](https://github.com/user-attachments/assets/79418d1f-6ccf-4901-bd27-b156d1021618)
![2024-10-24-151948_407x705_scrot](https://github.com/user-attachments/assets/ac8bf548-8ed3-43d3-a02a-fd6a839646ab)

I added a `td { max-width 90vw; }`. Not sure if that is the correct choice of unit.

Is this an improvement? Possibly a better default?

**Comment by lkhrs** [comment]
This isn't a good fit for upstream because not all tables are alike—different content, purpose, presentation needs, etc. It's best we leave this as a downstream implementation detail.
