### ISSUE TITLE
Having buttons that look like links

### ISSUE THREAD

**Issue by bas080** [kevquirk/simple.css#213]
Currently it is possible to make a link look like a button:
![2024-10-28-011115_777x672_scrot](https://github.com/user-attachments/assets/cab70eb5-c8b3-44b4-b3bc-9aff8403d17a)

I also have a use-case where I would like to do the opposite. The main reason that anchors are great for doing actual navigation with the browser and buttons are more appropriate (from a semantics pov) for doing things that hook into some JS.

I'm working on share buttons/links feature where some are actual links and others run some js on click. I don't feel comfortable writing `<a href="#">Call some Js on click</a>` because screenreaders will say that this is a link. I feel more confident writing `<button>Call some js on click</button>`. 

I could write everything as a button but then the progressive enhancement would suffer. 

I could write everything in links but then the semantics don't match the behavior of the browser.

**Comment by kevquirk** [comment]
So you want to make buttons look like links? Is that the gist of what you're saying?

If so, that isn't something we would implement in upstream. You would need to use [custom CSS](https://github.com/kevquirk/simple.css/wiki/Getting-Started-With-Simple.css#customise-simplecss) for that. If it were me, I'd probably just create a custom class of something like `button.no-styling` then style it as you see fit. All you'd need to use then is `<button class="no-styling">Call some js on click</button>`.

**Comment by bas080** [comment]
That is indeed the gist. I added some extra text to give more context and also give a common use-case where one would need buttons to look like anchors.

I believe it to be common enough that it makes sense to add this as a feature to simplecss.
