### ISSUE TITLE
Documentation: Prefer aria-current over .current

### ISSUE THREAD

**Issue by mrwweb** [kevquirk/simple.css#216]
I'm evaluating `simple.css` right now for use on some small personal projects. I love the approach!

I noticed that in the documentation for the `[.current` class](https://github.com/kevquirk/simple.css/wiki/Utility-elements-and-classes#current-nav-item), there is no mention of `aria-current`. I see that `aria-current` is supported in the styles already. Any time it's possible to [reward good accessibility with proper styles](https://adrianroselli.com/2021/06/using-css-to-enforce-accessibility.html), it feels like a no-brainer, and so updating the docs to prefer `aria-current` over `.current` whenever appropriate seems good.

I'd be happy to make the change, but I didn't see a way to edit or PR against the wiki.

**Comment by kevquirk** [comment]
Thanks for this - always happy to push for more accessible ways of doing things. I've updated the wiki page.
