### ISSUE TITLE
No indication when input disabled

### ISSUE THREAD

**Issue by fantostisch** [kevquirk/simple.css#25]
When an input is disabled:
```html
<input type="text" name="first_name" disabled="">
```
It looks the same and is thus indistinguishable from an input that is not disabled:
![image](https://user-images.githubusercontent.com/3309700/107863353-17c49700-6e54-11eb-8062-2830137a22b3.png)

It should be clear that the input is disabled. For example by changing the color:
```cs
input:disabled {
    background: #efefef;
}
```
![image](https://user-images.githubusercontent.com/3309700/107863387-53f7f780-6e54-11eb-920e-b260e690de75.png)

**Comment by kevquirk** [comment]
Hey thanks for this - I've just pushed a fix that changes the background colour in both light and dark mark, as well as using the `not-allowed` cursor for more visual effect.
