### ISSUE TITLE
nav ul styling

### ISSUE THREAD

**Issue by Kikketer** [kevquirk/simple.css#26]
Any thought around having the typical `nav ul li a` styling be the vertical menu?

```
nav ul {
  list-style: none;
  text-align: left;
  padding-left: 1rem;
}
nav ul li {
  border-bottom: 1px solid var(--border);
}
nav ul li:first-child {
  border-top: 1px solid var(--border);
}
nav ul a {
  margin: 0;
  border: none;
}
```

Today there's no vertical navigation and it seems to be a fairly common practice to make a nav-ul list when creating vertical menus.

**Comment by kevquirk** [comment]
I have no plans to add a vertical nav at the moment, sorry. If you add one yourself though, feel fee to create a PR and I'll consider adding it. :-)
