### ISSUE TITLE
Why the lack of components?

### ISSUE THREAD

**Issue by MartinsSilva** [kevquirk/simple.css#28]
Why don't you have classes for some very common styles in development, like "btn btn-primary" like bootstrap?

**Comment by kevquirk** [comment]
Not sure if you got the memo or not, but this is a CLASSLESS CSS framework. So adding classes would defeat that object. 😄 

Joking aside, I have been considering adding a "simple plus" stylesheet that has a couple of sensible classes in, like buttons, meta, nav and notice boxes. I haven't got around to implementing that yet though. Probably in the next month or so I'll have that done.

**Comment by MartinsSilva** [comment]
True, now I understand.

**Comment by flyweights** [comment]
```
<aside> SIDE </aside>
```
