### ISSUE TITLE
do not show <fieldset> border and remove margin/padding

### ISSUE THREAD

**Issue by fkooman** [kevquirk/simple.css#3]
```
fieldset {
    border: 0;
    padding: 0;
    margin: 0;
}
```

Without this any HTML using `<fieldset>` shows ugly borders and has additional padding/margin.

**Comment by chris-morgan** [comment]
Um… fieldset borders are a feature, *certainly* not a bug. To be sure there are certain modes of fieldset usage where you may legitimately remove the border of a fieldset, but I don’t think it’s a sensible default, especially not if the fieldset has a legend.

**Comment by kevquirk** [comment]
> Um… fieldset borders are a feature, _certainly_ not a bug. To be sure there are certain modes of fieldset usage where you may legitimately remove the border of a fieldset, but I don’t think it’s a sensible default, especially not if the fieldset has a legend.

Yeah, this is a good point actually. It's not hard to overwrite this in your own CSS, so I think I'll add this back in on the next release.

**Comment by fkooman** [comment]
As the original reporter I actually agree... was a bit of a silly request on my part. Thanks for calling it out!
