### ISSUE TITLE
Multiple header and footer tags

### ISSUE THREAD

**Issue by metbril** [kevquirk/simple.css#31]
As per the HTML5 spec, I use `<header>` and `<footer>` tags throughout my pages at multiple levels. Mostly at the page level and the article level. See below examples.

The `simple.css` style currently handles every header and footer identically. So any header for (in my case) section and article gets treated in a similar way. Therefor I need to fix every header and footer other then the main ones.

My suggestion would be to turn this around: make the current header and footer only work for the top level ones. This could be achieved simply (no pun intended) by addressing it as `body > header` and `body > footer` respectively.

I know I can fork and edit the css file, but I'd like to use the official CDN and apply as little customization as possible.

```html
<html>
  <head></head>
  <body>
    <header>
      <h1>Hello World</h1>
      <nav>
        <a href="/">Home</a>
        <a href="#">about</a>
      </nav>
    </header>
    <main>
      <section>
        <header>
          <h1>
            List header
          </h1>
        </header>
        <article>
          <header>
            <h2>Article 1</h2>
          </header>
          <p>Lorem ipsum...</p>
          <footer>
            <p>Published by /me</p>
          </footer>
        </article>
        <article>
          <header>
            <h2>Article 2</h2>
          </header>
          <p>Lorem ipsum...</p>
          <footer>
            <p>Published by /me</p>
          </footer>
        </article>
        <article>
          <header>
            <h2>Article 3</h2>
          </header>
          <p>Lorem ipsum...</p>
          <footer>
            <p>Published by /me</p>
          </footer>
        </article>
        <footer>
          <nav>
            <a href="#">Prev</a>
            <a href="#">Next</a>
          </nav>
        </footer>
      </section>
    </main>
    <footer>
      Copyright 2021 Etc.
    </footer>
  </body>
</html>
```

**Comment by kevquirk** [comment]
The whole point of Simple.css is to be a baseline for people to hack on top of. Vast majority of sites I've seen have a single header and footer, so I won't be implementing this change as the current setup appeals to the vast majority of use cases.

**Comment by metbril** [comment]
Thanks for the quick reply. Little disappointed, but I get it. Keep up the good work.

(I'll continue to steal some good idea's from the stylesheet, anyway.)

**Comment by kevquirk** [comment]
@metbril just revisiting this - I think I was a little hasty with my feedback here. I've just pushed a fix for this issue. You're right, other headers/footers shouldn't be impacted.

Thanks for raising it.
