### ISSUE TITLE
How to fit wide images?

### ISSUE THREAD

**Issue by beatquantum** [kevquirk/simple.css#35]
I am trying to include a wide image (3600x900) but it creates a horizontal scroll on the laptop. Ideally, the image should be contained within the device width with automatic scale-down. What should I do to the img section in the css? Thanks.

**Comment by kevquirk** [comment]
First of all, adding a really large image like that is bad web practice - the image should be the same size as the element you're displaying it in.

Within `<main>` the `img` tag already has a max-width of 100%, so it shouldn't cause any horizontal scrolling. Where are you actually adding the image? Can you give me a link so I can take a look?

**Comment by beatquantum** [comment]
Hi Kev, Would you mind if I email the link to you instead of adding here?

**Comment by kevquirk** [comment]
Sure - hi@kevq.uk

**Comment by kevquirk** [comment]
Closing as this is a website issue, not an Simple.css one.
