### ISSUE TITLE
Demo page doesn't use accessible labels

### ISSUE THREAD

**Issue by benaltair** [kevquirk/simple.css#40]
It's a small change, but you could link every `label` to the `input` using the [`for` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#attr-for). That way the label is clickable. Semantics, but could help encourage that in the wild, which helps people make more a11y friendly sites 😊

https://simplecss.org/demo
![image](https://user-images.githubusercontent.com/17771229/124987635-efe7f280-dff1-11eb-8d18-72f0ce11e2e0.png)
![image](https://user-images.githubusercontent.com/17771229/124987641-f1b1b600-dff1-11eb-829f-3092e5b8ab90.png)

**Comment by kevquirk** [comment]
Hi Ben,

The demo page is simply a mock-up of a form, and what you're talking about it all HTMl, so I don't understand what impact that would have on Simple.css as a project?

As you said though, it's a small change so I'll get it done at some point.

Thanks,

Kev

**Comment by benaltair** [comment]
Not a big deal like you say. On principle, Simple.css uses semantic HTML so well it would make sense to carry that through to the demo. I can submit a PR later too if needed.
