### ISSUE TITLE
button with a

### ISSUE THREAD

**Issue by gemal** [kevquirk/simple.css#41]
I tried to do:
`<button><a href="test">test</a></button>`

but I get:
![image](https://user-images.githubusercontent.com/69105/129903677-167750f7-bf4e-43ed-9981-a8269afac868.png)

**Comment by gemal** [comment]
btw: loove your project!

**Comment by kevquirk** [comment]
Hi @gemal,

There are a couple of ways to achieve a linked button. The first way, which is what many people do, is to add a class using a custom stylesheet. Something like this will work:

```
.button {
  border: none;
  border-radius: 5px;
  background: var(--accent);
  font-size: 1rem;
  color: var(--bg);
  padding: .7rem .9rem;
  margin: .5rem 0;
  transition: .4s;
}
```

Then you would add a standard link, but with the class of `button` to it's formatted to look like a button:

```
<a class="button" href="https://example.com">Click here</a>
```

If you prefer not to add custom CSS, then the alternative is to add a very simple line of inline JavaScript to your button that effectively makes the button a link. Like this:

```
<button onclick="window.location.href='https://example.com';">Click here</button>
```
