### ISSUE TITLE
how to?

### ISSUE THREAD

**Issue by Skynet132** [kevquirk/simple.css#43]
How do I enable dark mode for my webpage?

**Comment by jeferson0993** [comment]
you can do a togle buttom and use javascript to change the **prefers-color-scheme** to dark or simply change the default conlors :nerd_face: 

take a look on my repo for more :v: 
![preview](https://raw.githubusercontent.com/jeferson0993/simple.css/main/screenshot-mobile-dark-mode.png)

**Comment by kevquirk** [comment]
Simple.css uses prefers colour scheme so it selects which mode automatically depending on what theme your operating system is using.
