### ISSUE TITLE
Styling elements as buttons with role=button

### ISSUE THREAD

**Issue by jnv** [kevquirk/simple.css#46]
Hi, I have just started using simple.css for some prototyping and I love the ease of use!

One issue, which apparently is a continuous saga here (looking at #10, #41) is styling elements as buttons. The currently provided solutions are `<button onclick="">` and (undocumented, invalid) `<a><button>` nesting.

I would like to offer another approach with `role="button"` [ARIA attribute](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role). I am not quite sure if this is correct accessibility-wise, but I think it fits the goal of this library and allows easy styling for any element.

Would you be interested in PR for this change?

**Comment by kevquirk** [comment]
Yes, definitely. I need to set some time aside over the next few weeks to do some hacking on this project - there's lots I want to do, but I currently don't have time. Hopefully over Christmas I'll get around to making all these changes.

In the meantime, if you want to submit a PR, I'll take a look. Thanks.
