### ISSUE TITLE
(How to) Change the width to full width?

### ISSUE THREAD

**Issue by ldemailly** [kevquirk/simple.css#48]
I like the minimal styling but I don't like the fairly narrow main section; how do I make it have no more than x % of white space left and right of the main body? right now it seems hardcoded to some maximum width

**Comment by badcat** [comment]
I think changing or overriding the max-width (around line 67) to something wider than 45rem should work.

**Comment by kevquirk** [comment]
Change the `max-width` on the `body` element to be whatever you like.

**Comment by OfficerHalf** [comment]
For anyone looking at this later like me, I'm using this compromise:
```
:root {
  --reading-width: 45rem;
}

body {
  max-width: unset;
}
```

This way I can still limit the max-width when appropriate and even adjust it from view to view by changing the value of the variable if need be.
