### ISSUE TITLE
Unwanted triangle when using a multi select.

### ISSUE THREAD

**Issue by SamHennessy** [kevquirk/simple.css#49]
Great library, I really enjoy using it. I noticed a couple of things I thought I'd share:

The select input, when used in multi-select mode, I get the triangle when I would not want it:

![image](https://user-images.githubusercontent.com/119867/144688894-4d24d751-48cb-4097-8002-5707d31d3c31.png)

What I want:

![image](https://user-images.githubusercontent.com/119867/144688713-45d10c42-9e5b-4e1c-9bae-ab632051a648.png)

**Comment by kevquirk** [comment]
Thanks for letting me know. Should be fixed now.
