### ISSUE TITLE
[Feature Request] Admonitions

### ISSUE THREAD

**Issue by RoyiAvital** [kevquirk/simple.css#5]
This is a great and clean `CSS`.

Any chance of having Admonitions.  
Something like in Jupyter will be great: https://jupyterbook.org/content/content-blocks.html.

**Comment by kevquirk** [comment]
For that to work, I will need to add classes. I am, however, thinking about adding an additional "Simple+" css file that adds some reasonable classes, like notices, buttons etc.

By having an additional CSS file, it keeps the classes optional.
