### ISSUE TITLE
input type=date / time / datetime-local

### ISSUE THREAD

**Issue by lafeber** [kevquirk/simple.css#50]
Not really an issue, but It would be nice to also have these input types (date / time / datetime-local) in the demo.

Lots of developers don't know about them and include javascript pickers instead of just using the native ones!

PS: love the html accordion!

**Comment by kevquirk** [comment]
I've actually never had to implement those fields into a form either. I'll look into adding them though. Thanks for letting me know.

**Comment by kevquirk** [comment]
Won't get time to implement these. Feel free to push a PR.

**Comment by lafeber** [comment]
No problem! I would have pushed a PR if the html file was in the repository :)
