### ISSUE TITLE
Use Releases Tab

### ISSUE THREAD

**Issue by splch** [kevquirk/simple.css#52]
Hi!
Big fan of your work :) I was wondering if you could use the releases feature in GitHub for new updates on `simple.css` and `simple.min.css`. I'm using this stylesheet locally on my site and am hoping to watch for releases to know when to update.

**Comment by kevquirk** [comment]
Great idea! Something I've never looked into before and completely overlooked. I just started using it - it will track the NPM package version number, so we're currently at 1.1.2.

Thanks for the suggestion.

**Comment by splch** [comment]
Thanks so much!
