### ISSUE TITLE
button:hover opacity achieves the opposite desired outcome

### ISSUE THREAD

**Issue by Pyrolistical** [kevquirk/simple.css#53]
By decreasing the opacity of a button on hover it makes it _less_ clickable.

I propose to replace it a filter that increases brightness on hover.

#### Before
<img width="232" alt="Screen Shot 2022-01-14 at 4 02 10 PM" src="https://user-images.githubusercontent.com/463642/149599931-13240a58-5c98-47c9-8d19-1456b782819b.png">

#### After
<img width="213" alt="Screen Shot 2022-01-14 at 3 56 08 PM" src="https://user-images.githubusercontent.com/463642/149599734-77d231ca-ed25-4567-9772-b48f8a4e1b5f.png">

This replaces [`opacity: 0.8;`](https://github.com/kevquirk/simple.css/blob/e2780a39819eef248dfe8f22ed4a9b6b55211f46/simple.css#L254) with `filter: brightness(1.2);`

**Comment by kevquirk** [comment]
Thanks for this, I just pushed a fix - I was never happy with opacity, so this helps.
