### ISSUE TITLE
Is there a light/dark mode only version?

### ISSUE THREAD

**Issue by Trim21** [kevquirk/simple.css#54]
Just like https://github.com/sindresorhus/github-markdown-css has a `github-markdown-light.css` and `github-markdown-dark.css` to force light or dark mode. It there a `simple-{light,dark}.css` to force color theme?

**Comment by kevquirk** [comment]
No. But you could easily amend the CSS in your project to use either dark or light. Just add a custom css file then change the variables to be whichever colour scheme you want.

More here on customising: https://simplecss.org/getting-started#make-changes

**Comment by ryansabin** [comment]
I know this is closed. But, this link is broken.

**Comment by kevquirk** [comment]
Here's the update link - https://github.com/kevquirk/simple.css/wiki/Getting-Started-With-Simple.css#customise-simplecss
