### ISSUE TITLE
please update the vercel link the repo desciption with simplecss.org

### ISSUE THREAD

**Issue by pr0PM** [kevquirk/simple.css#58]
please update the vercel link the desciption with the new one https://simplecss.org

**Comment by pr0PM** [comment]
<img width="439" alt="image" src="https://user-images.githubusercontent.com/44268366/150669967-21ef25f7-9a83-4c8d-9835-ede96ca4d6ea.png">

**Comment by kevquirk** [comment]
Thanks for that. I didn’t even realise vermeil had changed it!
