### ISSUE TITLE
cursor:pointer for buttons

### ISSUE THREAD

**Issue by fkooman** [kevquirk/simple.css#6]
The cursor does not change to a pointer when hovering over a button. Tested in Firefox and Chromium. You can make the pointer explicit, like what was already done for `<summary>`.

```
a button,
button,
input[type="submit"],
input[type="reset"],
input[type="button"] {
  /* ... */ 
  cursor: pointer;
}
```

**Comment by pbarney** [comment]
Then you'll probably want to add it to `nav a` as well.

**Comment by fkooman** [comment]
> Then you'll probably want to add it to `nav a` as well.

Doesn't `<a>` already have pointer by default on _hover_? It works the links in my `<nav>` in any case...

**Comment by krisu5** [comment]
There's historic reason why buttons don't have pointer cursor: https://ux.stackexchange.com/questions/105024/why-dont-button-html-elements-have-a-css-cursor-pointer-by-default/105027#105027

**Comment by kevquirk** [comment]
Won't be changing this - buttons shouldn't have a pointer IMO, per @krisu5 comment.

**Comment by pbarney** [comment]
> Doesn't `<a>` already have pointer by default on _hover_? It works the links in my `<nav>` in any case...

I think you fell into the same misunderstanding I had when I first commented, confusing pointer (the hand with a finger) with the default cursor (the arrow). I had thought the buttons were showing the text selection cursor.

I agree with @kevquirk closing this.

**Comment by fkooman** [comment]
Fair enough! :)
