### ISSUE TITLE
Minified file in NPM package is v1 styles

### ISSUE THREAD

**Issue by OfficerHalf** [kevquirk/simple.css#60]
Title should make it clear. There are three files in the npm package:

- `simple.css`
- `simple.min.css`
- `simple-v1.css`

`simple.min.css` is the minified version of the V1 styles, not the latest.

**Comment by kevquirk** [comment]
Not sure if that's a caching issues on your side, but the 4 files are definitely different:

```
https://unpkg.com/simpledotcss@2.0.1/simple-v1.min.css
https://unpkg.com/simpledotcss@2.0.1/simple-v1.min.css
https://unpkg.com/simpledotcss@2.0.1/simple-v1.min.css
https://unpkg.com/simpledotcss@2.0.1/simple-v1.min.css

**Comment by OfficerHalf** [comment]
Aha, didn't see the 2.0.1 version since it wasn't listed here as a release. Fixed in that version, thanks.
