### ISSUE TITLE
nav link/form button not same size

### ISSUE THREAD

**Issue by fkooman** [kevquirk/simple.css#61]
![image](https://user-images.githubusercontent.com/616885/151969258-ffafae72-0dea-40b2-905e-2e82f5cc4677.png)

form button and nav button are not same size, use case:

```
<body>
    <header>
        <h1>My Site</h1>
        <nav>
            <a href="/">Home</a>
            <form method="post" action="/logout">
                <button type="submit">Logout</button>
            </form>
        </nav>
    </header>
    
    ...
```

Perhaps there's other ways of accomplishing this? Perhaps this is intentional? 

The logout action is a POST and not a GET that's why I can't use a link...

**Comment by kevquirk** [comment]
Not sure why they would need to be? They're completely different elements.
