### ISSUE TITLE
Removing the top margin of the first element following the summary

### ISSUE THREAD

**Issue by oldrup** [kevquirk/simple.css#62]
Not an issue, just sharing a tweak needed in my use case.

WordPress Gutenberg or my theme, adds top margin to the first heading in a container. Makes good sense in a blog post, but looks off in the Details / Summary accordion.

This little addition to the style sheet, takes care of removing the top margin of any first element following the summary.

`
details[open] summary + * {
  margin-top: 0;
}
`

Screenshot when applied:
![image](https://user-images.githubusercontent.com/17141205/152641583-d09563fd-4515-41f0-a17e-a03f1aac705b.png)

**Comment by kevquirk** [comment]
Ah, that's a great tweak, thank you! I'll commit it today.

Hadn't come across that one as I haven't used a header at the top of a `details` element. Really appreciate the feedback. 👍

**Comment by oldrup** [comment]
Glad you could use it, and thank you for sharing your work. It's quite inspirational. Definitely going to experiment with more class-less styling.
