### ISSUE TITLE
Zola theme built with simple.css

### ISSUE THREAD

**Issue by tarunjana** [kevquirk/simple.css#64]
First of all, thank you so much for this amazing project.

I've created a [Zola](https://www.getzola.org) theme built with simple.css

Here is the project repo: https://github.com/tarunjana/simplify

You may consider to add this theme to the showcase page. 😄

**Comment by kevquirk** [comment]
Thanks for this, but i'm trying to showcase sites that have done something with Simple.css, rather than just implement it as it.
