### ISSUE TITLE
Demo site broken

### ISSUE THREAD

**Issue by milankragujevic** [kevquirk/simple.css#66]
The website https://simplecss.org/ looks broken due to the CSS file missing on cdn.simplecss.org

https://cdn.simplecss.org/simple.css

![image](https://user-images.githubusercontent.com/7611163/154017172-e07b1d51-af18-4880-a44f-15b25439006b.png)

![image](https://user-images.githubusercontent.com/7611163/154017226-cbc84bdd-7d8b-4a83-9476-e89b14067c25.png)

**Comment by kevquirk** [comment]
It looks to be working for me. To test it's not cached for me, I just did a GTMetrix scan and the CSS is rendering fine.

https://gtmetrix.com/reports/simplecss.org/YWqJSIsQ/

Looks like an issue on your end to me. Do you have an over-zealous content blocker or something?

**Comment by izerozlu** [comment]
It's fine by me as well. It should be something on your side @milankragujevic.

**Comment by milankragujevic** [comment]
Works fine now, but before the https://cdn.simplecss.org/simple.css link was returning an error:

![image](https://user-images.githubusercontent.com/7611163/154032372-ffe71fb6-df3e-4d9f-9887-bb054b351861.png)

Closing as it's resolved by itself.

**Comment by izerozlu** [comment]
Maybe it was about a temporary hickup on the CDN side?

**Comment by kevquirk** [comment]
Yeah, wonder if Netlify had a little brain fart.
