### ISSUE TITLE
Some inline tags have a fixed size, irrespective of their container's font size

### ISSUE THREAD

**Issue by pbarney** [kevquirk/simple.css#67]
**Version:** latest as of 2022-02-16 of both simple.css and simple-v1.css

**Problem:** Some inline tags have a fixed size, irrespective of their container or context, including `<code>`,`<pre>`,`<kbd>`, and `<samp>`

**Example:** https://jsfiddle.net/pbarney/kL7a3b8m/1/

Content in `<code>` tag is significantly smaller than the rest of the text in the H1 element.

**Suggested solution:** perhaps use `em` rather than `rem` on those inline tags?

**Comment by kevquirk** [comment]
Just pushed a fix for this. Thanks.
