### ISSUE TITLE
750px vs 720px

### ISSUE THREAD

**Issue by metbril** [kevquirk/simple.css#73]
Why is this at 750px and all others at 720px?

(I'm a CSS noob)

https://github.com/kevquirk/simple.css/blob/357a05ea2bb3458b55a79141af4c120734c5010d/simple.css#L246

**Comment by Jieiku** [comment]
if it was overlooked by accident when updating values, then I would argue that using sass and variables could have prevented this.

**Comment by kevquirk** [comment]
Thanks for this and apologies for the delay in reply. It was an oversight, which I've just fixed.
