### ISSUE TITLE
Toggle button to switch to dark mode

### ISSUE THREAD

**Issue by rohitfarmer** [kevquirk/simple.css#77]
Hi Kev, thanks for this awesome resource. My website can toggle between dark and light modes based on the browser settings, but is there a way to put a toggle switch on the website itself that users can use to switch between the modes independent of the browser settings? Thanks!

**Comment by kevquirk** [comment]
Hey Rohit,

It's something that can be implemented in a number of ways relatively easily. However, it's outside the scope of this project, but there are lots of great guides on how to do it online.

Thanks,

Kev

**Comment by mendhak** [comment]
@rohitfarmer  did you ever implement something for this? As far as I can understand JS can be used to set different classes but can't switch the  `@media (prefers-color-scheme: dark)` part.  Did you end up duplicating the variables into another CSS class?

**Comment by rohitfarmer** [comment]
@mendhak I just set it up to be in always dark mode. I tried a few things, but none looked very clean, so I gave up. I am sure it's trivial for someone good at UI. I don't have the skills.

**Comment by kevquirk** [comment]
Something [like this](https://coliff.github.io/dark-mode-switch/) will probably help.
