### ISSUE TITLE
Multiple `nav` tag creates issue

### ISSUE THREAD

**Issue by tarunjana** [kevquirk/simple.css#81]
The style for the first `nav` tag in the page is extremely good. But sometimes we need multiple `nav` tag in a page. For example, Hugo automatically creates a `nav` tag for *Table of Contents*. Here is the [reference](https://gohugo.io/content-management/toc/#usage).

Unfortunately, simple.css treats every `nav` tag similarly. As a result, the table of contents does not look good.

![image](https://user-images.githubusercontent.com/76617446/166401172-b173f5c3-7d07-4641-9cc5-1bc899262772.png)

**Comment by kevquirk** [comment]
Just pushed a fix that should resolve the issue. Only `nav` elements within the `header` will be formatted. So additional `nav` elements won't be. Then you can format them yourself using custom css.
