### ISSUE TITLE
table in details

### ISSUE THREAD

**Issue by marek22k** [kevquirk/simple.css#87]
Especially with large tables I find this useful. However, it looks a bit strange when I tried it:
![pic](https://user-images.githubusercontent.com/46723399/170891568-8a07d8b7-941a-462a-97a4-77656168490f.png)

**Comment by kevquirk** [comment]
Sorry for the delay on this. I'll do some testing and will push a fix as soon as I get time.

**Comment by lkhrs** [comment]
Hi @marek22k, are you still experiencing this issue? I can't reproduce this myself on 2.1.0 and the latest from the CDN.

I need more details:
- Browser and version
- Simple.css version
- CSS used for `<table>`

Pictured below is Firefox 103, Edge 103, and Safari 15.5.
<img width="1865" alt="jgTPVmli" src="https://user-images.githubusercontent.com/1342461/178564387-1a5cd6c3-996e-4dae-926c-48cdb8f5c4c5.png">

**Comment by marek22k** [comment]
I have updated simple.css and now the problem is no longer there. Thanks a lot!
