### ISSUE TITLE
index.html is not responsive

### ISSUE THREAD

**Issue by Ivan-Kouznetsov** [kevquirk/simple.css#89]
The repo would be improved by having an minimal html page that demonstrates the responsiveness of the style sheet, the `index.html` currently in the repo does not appear to do that.

The attachment shows that the margins remain when viewing `index.html` using the iPhone SE screen size in Chrome.

![not responsive](https://user-images.githubusercontent.com/52215050/177294226-974c47e1-9227-4c86-aa52-0180fcf745ad.png)

**Comment by kevquirk** [comment]
Visit https://simplecss.org
