### ISSUE TITLE
Should tables use display: table instead of display:block?

### ISSUE THREAD

**Issue by pwaring** [kevquirk/simple.css#92]
If I create a table using simple.css, it doesn't always have enough space for the contents of each cell. For example, in this screenshot you can see that the cell with the `select` element isn't large enough, so the dropdown icon of the select clashes with the option text:

![simple-css-display-block](https://user-images.githubusercontent.com/433556/178138446-53cc7585-d4f6-4bdb-bf1f-edaf1aaef70c.png)

The HTML for the table is:

```html
<table>
    <thead>
        <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Response</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Friday 15th July 2022</td>
            <td>10:00am</td>
            <td>
                <select name="responses[3]">
                    <option value="-1"></option>
                    <option value="0">No</option>
                    <option value="2">Yes</option>
                    <option value="1">Maybe</option>
                </select>
            </td>
        </tr>
        <tr>
            <td>Monday 18th July 2022</td>
            <td>10:00am</td>
            <td>
                <select name="responses[4]">
                    <option value="-1"></option>
                    <option value="0">No</option>
                    <option value="2">Yes</option>
                    <option value="1">Maybe</option>
                </select>
            </td>
        </tr>
        <tr>
            <td>Thursday 21st July 2022</td>
            <td>10:00am</td>
            <td>
                <select name="responses[5]">
                    <option value="-1"></option>
                    <option value="0">No</option>
                    <option value="2">Yes</option>
                    <option value="1">Maybe</option>
                </select>
            </td>
        </tr>
    </tbody>
</table>
```

After a bit of digging in the developer console, I realised that all tables had the style `display: block`. Changing it to `display: table` resulted in a table that had space for every cell:

![simple-css-display-table](https://user-images.githubusercontent.com/433556/178138555-0176c657-6c79-418f-a369-6e2fa613c5e3.png)

My CSS knowledge is limited so I don't know if `display: block` has been chosen for a specific reason or use case. For now I'm using an overriding CSS file to switch all table elements to `display: table`, but this might be useful for other people who come across the same problem.

P.S. Thanks for creating this project, I use it in a lot of places where I want to put together a simple website or landing page and it's saved me a lot of time compared with large CSS frameworks.

**Comment by lkhrs** [comment]
You're correct, `display: table` (the browser default) should be used instead of `display: block`, because screenreaders will have [trouble](https://developer.mozilla.org/en-US/docs/Web/CSS/display#tables) with tables that have `display` values such as `block`, `grid`, and `flex`.

Currently, tables are set to `display:block` so they're responsive on mobile. It looks like the best way to solve this is to wrap the table in a scrollable element + add keyboard nav support, but I'm still working out the specifics.

Your specific issue though is related to a lack of minimum width on input elements on top of a 60% width within the parent box on desktop. I opened #93 with a fix.
