### ISSUE TITLE
Form inputs in the header/footer are off-center

### ISSUE THREAD

**Issue by rsonger** [kevquirk/simple.css#94]
> Hi, first-time contributor here. Thanks for this awesome project! It really saves me a lot of time so I can focus on the backend of my project :)

The rules for `input, select, textarea` apply a `1rem` right margin that pushes the form controls off-center when placed in center-aligned regions such as headers and footers.

The screenshot below shows a language select form placed in the footer of a page. The select control has a 16-pixel right margin pushing it off-center as can be seen relative to the submit button and paragraph below it. 

![Screen Shot 2022-07-14 at 10 45 23](https://user-images.githubusercontent.com/1834840/178869845-33376601-f6b4-4dbe-b7c4-bf8b640c70e9.png)

Here is HTML source that produced the effect in Chrome v103:
```html
<footer>
  <form action="/setlang/" method="post">
    <select name="language">
      <option value="en" selected="">
        English (en)
      </option>
      <option value="ja">
        日本語 (ja)
      </option>
    </select>
    <input type="submit" value="Go">
  </form>            
  <p>Request received: July 14, 2022, 10:44 a.m.</p>
</footer>
```

The submit button does not have the right margin applied due to a separate `margin` rule applied elsewhere under the `input[type="submit"]` selector. That slight difference is how I was able to notice this issue in the first place.

Perhaps creating a ruleset just for the textarea, input, and select controls inside headers and footers is the best solution?

**Comment by lkhrs** [comment]
This was added in #93 to fix a weird Firefox bug:
![image](https://user-images.githubusercontent.com/1342461/178895398-c68fda42-5096-4be5-a5a1-33942168040e.png)

To reduce complexity and future bugs, I think we should either let the browser set the input field widths (option A), or set them to 100% (option B). Option A would look more uniform. If we go with option B, users can control the initial width by using the `size=""` attribute in `<input>`.
