### ISSUE TITLE
Header, nav bar, and asides don't fit well on mobile

### ISSUE THREAD

**Issue by binyomen** [kevquirk/simple.css#96]
Hey!

First of all, amazing project! This has been super helpful to me in setting up random small sites.

I've noticed that some aspects of the side have some issues on mobile, and I figured I'd put the ones I noticed into this issue.

Here's my HTML:

```html
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="[https://cdn.simplecss.org/simple.min.css](view-source:https://cdn.simplecss.org/simple.min.css)">

    <title>Test for rpgnotes - Aside test</title>
  </head>

  <body>
    <header>
      <h1>Test for rpgnotes</h1>
      <nav>
        <ul>
          <li><a href="[/](view-source:http://localhost:8000/)">Home</a></li>
          <li><a href="[/journals/](view-source:http://localhost:8000/journals/)">Journals</a></li>
          <li><a href="[/characters/](view-source:http://localhost:8000/characters/)">Characters</a></li>
          <li><a href="[/npcs/](view-source:http://localhost:8000/npcs/)">NPCs</a></li>
          <li><a href="[/locations/](view-source:http://localhost:8000/locations/)">Locations</a></li>
          <li><a href="[/factions/](view-source:http://localhost:8000/factions/)">Factions</a></li>
          <li><a href="[/items/](view-source:http://localhost:8000/items/)">Items</a></li>
          <li><a href="[/uncategorised/](view-source:http://localhost:8000/uncategorised/)">Uncategorised</a></li>
        </ul>
      </nav>
    </header>

    <main>
      <h2>Aside test</h2>
      <p>Here's some text.</p>
      <aside><p>Here's an aside!</p></aside>
      <p>Here's some more text.</p>
    </main>

    <footer>
      Built Fri Jul 15 2022 23:27:22 GMT-0700 (Pacific Daylight Time)
    </footer>
  </body>
</html>
```

And here's an image of it emulating an iPhone (on Firefox 102.0.1):

![image](https://user-images.githubusercontent.com/2928612/179343570-b4613e2c-135e-471a-a01b-4efee594c439.png)

To my thinking, the header should be wrapping, the nav bar at the top should distinguish the links better/flow them to a new line, and the aside should be inline with the text.

Here it is with desktop sizing:

![image](https://user-images.githubusercontent.com/2928612/179343651-630087e1-ee58-43b7-a2a4-6556d1fcb37a.png)

I can try to open a PR/PRs for this this weekend unless someone gets to it first.

**Comment by lkhrs** [comment]
Looks like it's related to wrapping navigation links with list items – which is the semantic way to do it, you're not doing anything wrong there 😀

I'm testing a fix now to push later.

I think on mobile, we should make asides full-width:

<img width="348" alt="G7g6s46V" src="https://user-images.githubusercontent.com/1342461/179363999-35a2751a-f7ba-43b4-839b-6eb597e5fe4f.png">

**Comment by binyomen** [comment]
Thanks for taking a look at this so quickly! That all seems like good behavior to me.
